-- SKY Tech Dynamic — database schema
--
-- Generated from src/lib/server/schema.ts. Do not edit this file; edit the
-- schema and run `npm run db:sql` again.
--
-- To apply to a NEW database: hPanel > Databases > phpMyAdmin > select the
-- database > SQL tab, paste everything below, press Go. To add a single later
-- migration to a database that already has tables, use drizzle/apply/ instead.

-- 0000_initial.sql
CREATE TABLE `email_queue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`enquiry_id` int,
	`to_address` varchar(254) NOT NULL,
	`reply_to` varchar(254) NOT NULL,
	`subject` varchar(255) NOT NULL,
	`body_text` text NOT NULL,
	`status` enum('pending','sent','failed') NOT NULL DEFAULT 'pending',
	`attempts` int NOT NULL DEFAULT 0,
	`last_error` varchar(500) NOT NULL,
	`next_attempt_at` datetime NOT NULL,
	`created_at` datetime NOT NULL,
	`sent_at` datetime,
	CONSTRAINT `email_queue_id` PRIMARY KEY(`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `enquiries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reference` varchar(24) NOT NULL,
	`name` varchar(100) NOT NULL,
	`company` varchar(120) NOT NULL,
	`email` varchar(254) NOT NULL,
	`phone` varchar(30) NOT NULL,
	`country` varchar(80) NOT NULL,
	`service` varchar(60) NOT NULL,
	`details` text NOT NULL,
	`budget` varchar(80) NOT NULL,
	`budget_custom` varchar(80) NOT NULL,
	`timeline` varchar(80) NOT NULL,
	`enquiry_type` varchar(20) NOT NULL,
	`package_name` varchar(160) NOT NULL,
	`add_ons` text NOT NULL,
	`estimate` varchar(120) NOT NULL,
	`status` enum('new','read','replied','archived') NOT NULL DEFAULT 'new',
	`admin_notes` text,
	`ip_hash` varchar(64) NOT NULL,
	`user_agent` varchar(255) NOT NULL,
	`created_at` datetime NOT NULL,
	`updated_at` datetime NOT NULL,
	CONSTRAINT `enquiries_id` PRIMARY KEY(`id`),
	CONSTRAINT `enquiries_reference_unique` UNIQUE(`reference`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `rate_limits` (
	`bucket` varchar(120) NOT NULL,
	`hits` int NOT NULL DEFAULT 0,
	`window_started_at` datetime NOT NULL,
	CONSTRAINT `rate_limits_bucket` PRIMARY KEY(`bucket`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX `email_queue_due_idx` ON `email_queue` (`status`,`next_attempt_at`);
CREATE INDEX `enquiries_status_created_idx` ON `enquiries` (`status`,`created_at`);
CREATE INDEX `enquiries_created_idx` ON `enquiries` (`created_at`);

-- 0001_admin.sql
CREATE TABLE `admin_sessions` (
	`token_hash` varchar(64) NOT NULL,
	`user_id` int NOT NULL,
	`expires_at` datetime NOT NULL,
	`ip_hash` varchar(64) NOT NULL,
	`user_agent` varchar(255) NOT NULL,
	`created_at` datetime NOT NULL,
	CONSTRAINT `admin_sessions_token_hash` PRIMARY KEY(`token_hash`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `admin_users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`email` varchar(254) NOT NULL,
	`name` varchar(100) NOT NULL,
	`password_hash` varchar(255) NOT NULL,
	`totp_secret` varchar(64),
	`totp_last_step` int,
	`role` enum('owner','editor') NOT NULL DEFAULT 'editor',
	`is_active` int NOT NULL DEFAULT 1,
	`failed_attempts` int NOT NULL DEFAULT 0,
	`locked_until` datetime,
	`last_login_at` datetime,
	`created_at` datetime NOT NULL,
	`updated_at` datetime NOT NULL,
	CONSTRAINT `admin_users_id` PRIMARY KEY(`id`),
	CONSTRAINT `admin_users_email_unique` UNIQUE(`email`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `audit_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int,
	`actor` varchar(254) NOT NULL,
	`action` varchar(60) NOT NULL,
	`target` varchar(120) NOT NULL,
	`detail` varchar(500) NOT NULL,
	`ip_hash` varchar(64) NOT NULL,
	`created_at` datetime NOT NULL,
	CONSTRAINT `audit_log_id` PRIMARY KEY(`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX `admin_sessions_user_idx` ON `admin_sessions` (`user_id`,`expires_at`);
CREATE INDEX `audit_log_created_idx` ON `audit_log` (`created_at`);

-- 0002_clients.sql
CREATE TABLE `client_services` (
	`id` int AUTO_INCREMENT NOT NULL,
	`client_id` int NOT NULL,
	`service` varchar(60) NOT NULL,
	`package_name` varchar(160) NOT NULL,
	`amount` decimal(10,2) NOT NULL,
	`billing` enum('once','monthly','yearly') NOT NULL DEFAULT 'once',
	`status` enum('proposed','active','completed','cancelled') NOT NULL DEFAULT 'proposed',
	`started_on` datetime,
	`ends_on` datetime,
	`notes` text,
	`created_at` datetime NOT NULL,
	`updated_at` datetime NOT NULL,
	CONSTRAINT `client_services_id` PRIMARY KEY(`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `clients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`company` varchar(120) NOT NULL,
	`email` varchar(254) NOT NULL,
	`phone` varchar(30) NOT NULL,
	`country` varchar(80) NOT NULL,
	`status` enum('lead','active','past','lost') NOT NULL DEFAULT 'lead',
	`source_enquiry_id` int,
	`notes` text,
	`created_at` datetime NOT NULL,
	`updated_at` datetime NOT NULL,
	CONSTRAINT `clients_id` PRIMARY KEY(`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE `email_queue` ADD `client_id` int;
ALTER TABLE `email_queue` ADD `sent_by` int;
ALTER TABLE `email_queue` ADD `kind` enum('notification','reply') DEFAULT 'notification' NOT NULL;
ALTER TABLE `enquiries` ADD `estimate_once` int DEFAULT 0 NOT NULL;
ALTER TABLE `enquiries` ADD `estimate_monthly` int DEFAULT 0 NOT NULL;
ALTER TABLE `enquiries` ADD `estimate_yearly` int DEFAULT 0 NOT NULL;
ALTER TABLE `enquiries` ADD `estimate_open` int DEFAULT 0 NOT NULL;
CREATE INDEX `client_services_client_idx` ON `client_services` (`client_id`,`status`);
CREATE INDEX `clients_status_idx` ON `clients` (`status`,`created_at`);
CREATE INDEX `clients_email_idx` ON `clients` (`email`);

-- 0003_settings.sql
CREATE TABLE `site_settings` (
	`setting_key` varchar(60) NOT NULL,
	`value` text NOT NULL,
	`updated_at` datetime NOT NULL,
	`updated_by` int,
	CONSTRAINT `site_settings_setting_key` PRIMARY KEY(`setting_key`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 0004_prices.sql
CREATE TABLE `service_prices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`service_name` varchar(60) NOT NULL,
	`package_name` varchar(160) NOT NULL,
	`price` varchar(40) NOT NULL,
	`updated_at` datetime NOT NULL,
	`updated_by` int,
	CONSTRAINT `service_prices_id` PRIMARY KEY(`id`),
	CONSTRAINT `service_prices_item_idx` UNIQUE(`service_name`,`package_name`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 0005_page_text.sql
CREATE TABLE `page_text` (
	`id` int AUTO_INCREMENT NOT NULL,
	`page_key` varchar(80) NOT NULL,
	`field_key` varchar(120) NOT NULL,
	`value` text NOT NULL,
	`updated_at` datetime NOT NULL,
	`updated_by` int,
	CONSTRAINT `page_text_id` PRIMARY KEY(`id`),
	CONSTRAINT `page_text_field_idx` UNIQUE(`page_key`,`field_key`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 0006_account_security.sql
CREATE TABLE `admin_recovery_codes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`code_hash` varchar(64) NOT NULL,
	`used_at` datetime,
	`created_at` datetime NOT NULL,
	CONSTRAINT `admin_recovery_codes_id` PRIMARY KEY(`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `password_resets` (
	`token_hash` varchar(64) NOT NULL,
	`user_id` int NOT NULL,
	`expires_at` datetime NOT NULL,
	`used_at` datetime,
	`ip_hash` varchar(64) NOT NULL,
	`created_at` datetime NOT NULL,
	CONSTRAINT `password_resets_token_hash` PRIMARY KEY(`token_hash`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `section_visibility` (
	`id` int AUTO_INCREMENT NOT NULL,
	`page_key` varchar(80) NOT NULL,
	`section_key` varchar(60) NOT NULL,
	`device` varchar(20) NOT NULL,
	`hidden` int NOT NULL DEFAULT 0,
	`updated_at` datetime NOT NULL,
	`updated_by` int,
	CONSTRAINT `section_visibility_id` PRIMARY KEY(`id`),
	CONSTRAINT `section_visibility_idx` UNIQUE(`page_key`,`section_key`,`device`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE `admin_users` ADD `pending_totp_secret` varchar(64);
CREATE INDEX `admin_recovery_user_idx` ON `admin_recovery_codes` (`user_id`,`used_at`);
CREATE INDEX `password_resets_user_idx` ON `password_resets` (`user_id`,`expires_at`);

-- 0007_analytics.sql
CREATE TABLE `page_views` (
	`id` int AUTO_INCREMENT NOT NULL,
	`day` varchar(10) NOT NULL,
	`path` varchar(255) NOT NULL,
	`referrer` varchar(120) NOT NULL,
	`device` enum('mobile','desktop') NOT NULL,
	`visitor_hash` varchar(64) NOT NULL,
	`created_at` datetime NOT NULL,
	CONSTRAINT `page_views_id` PRIMARY KEY(`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX `page_views_day_idx` ON `page_views` (`day`);
CREATE INDEX `page_views_path_idx` ON `page_views` (`day`,`path`);

-- 0008_admin_invite.sql
ALTER TABLE `admin_users` ADD `must_change_password` int DEFAULT 0 NOT NULL;

-- 0009_trusted_devices.sql
CREATE TABLE `trusted_devices` (
	`token_hash` varchar(64) NOT NULL,
	`user_id` int NOT NULL,
	`expires_at` datetime NOT NULL,
	`ip_hash` varchar(64) NOT NULL,
	`user_agent` varchar(255) NOT NULL,
	`last_used_at` datetime,
	`created_at` datetime NOT NULL,
	CONSTRAINT `trusted_devices_token_hash` PRIMARY KEY(`token_hash`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX `trusted_devices_user_idx` ON `trusted_devices` (`user_id`,`expires_at`);
