/* Turns the migrations drizzle-kit generates into SQL that can be run directly.

   Two things have to change on the way. Drizzle separates statements with a
   `--> statement-breakpoint` marker, which is not a valid MySQL comment (a
   comment needs `--` followed by a space), so it is stripped — it appears both
   on its own line and appended to a statement. And drizzle does not emit a
   character set, so utf8mb4 is added to each table; without it a name or a
   message containing an emoji or an accented character is rejected.

   Run: npm run db:sql

   Writes two things:
     drizzle/apply-in-phpmyadmin.sql  every migration, for a fresh database
     drizzle/apply/<name>.sql         one file each, to add to an existing one */

import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = "drizzle";
const APPLY_DIR = join(DIR, "apply");
const OUT = join(DIR, "apply-in-phpmyadmin.sql");
const CHARSET = ") DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;";
const BREAKPOINT = /-->\s*statement-breakpoint/g;

const files = readdirSync(DIR)
  .filter((f) => /^\d{4}_.*\.sql$/.test(f))
  .sort();

if (files.length === 0) {
  console.error("No migrations found. Run `npm run db:generate` first.");
  process.exit(1);
}

const clean = (file) =>
  readFileSync(join(DIR, file), "utf8")
    .replace(BREAKPOINT, "")
    .split("\n")
    .filter((line) => line.trim() !== "")
    // A line that is exactly ");" closes a CREATE TABLE; a CREATE INDEX closes
    // on the same line as its statement, so it is untouched.
    .map((line) => (line.trim() === ");" ? CHARSET : line))
    .join("\n")
    .trim();

mkdirSync(APPLY_DIR, { recursive: true });
for (const file of files) {
  writeFileSync(join(APPLY_DIR, file), `${clean(file)}\n`, "utf8");
}

const header = `-- SKY Tech Dynamic — database schema
--
-- Generated from src/lib/server/schema.ts. Do not edit this file; edit the
-- schema and run \`npm run db:sql\` again.
--
-- To apply to a NEW database: hPanel > Databases > phpMyAdmin > select the
-- database > SQL tab, paste everything below, press Go. To add a single later
-- migration to a database that already has tables, use drizzle/apply/ instead.

`;

const body = files.map((file) => `-- ${file}\n${clean(file)}`).join("\n\n");
writeFileSync(OUT, `${header}${body}\n`, "utf8");
console.log(`Wrote ${OUT} and ${files.length} file(s) in ${APPLY_DIR}/`);
